-- ── 1. Tabla propiedades ────────────────────────────────────────────────────
create table public.propiedades (
  id            bigint generated by default as identity primary key,
  ref           text        not null unique,
  titulo        text        not null,
  tipo          text        not null,
  zona          text        not null,
  barrio        text        not null default '',
  direccion     text        not null default '',
  precio        numeric     not null default 0,
  m2            numeric     not null default 0,
  habitaciones  int         null,
  banos         int         null,
  planta        text        null,
  terraza       boolean     not null default false,
  garage        boolean     not null default false,
  ascensor      boolean     not null default false,
  piscina       boolean     not null default false,
  imagen        text        not null default '',
  imagenes      text[]      not null default '{}',
  badge         text        null,
  descripcion   text        not null default '',
  caracteristicas text[]    not null default '{}',
  energia       text        not null default 'D',
  lat           float8      not null default 41.3874,
  lng           float8      not null default 2.1686,
  publicado     boolean     not null default false,
  created_at    timestamptz not null default now()
);

-- Acceso público de lectura (solo propiedades publicadas)
alter table public.propiedades enable row level security;

create policy "Lectura pública de propiedades publicadas"
  on public.propiedades for select
  using (publicado = true);

create policy "Admin puede todo"
  on public.propiedades for all
  using (true)
  with check (true);

-- ── 2. Bucket de fotos ───────────────────────────────────────────────────────
-- Ejecutar en Storage > New bucket: nombre "propiedades", public = true
-- O con SQL:
insert into storage.buckets (id, name, public)
values ('propiedades', 'propiedades', true)
on conflict do nothing;

create policy "Fotos públicas"
  on storage.objects for select
  using (bucket_id = 'propiedades');

create policy "Admin puede subir fotos"
  on storage.objects for insert
  with check (bucket_id = 'propiedades');

create policy "Admin puede borrar fotos"
  on storage.objects for delete
  using (bucket_id = 'propiedades');
