-- ── Ejecutar en Supabase SQL Editor ─────────────────────────────────────────
-- Añadir a las tablas ya creadas en supabase_schema.sql

-- ── Tabla leads ─────────────────────────────────────────────────────────────
create table if not exists public.leads (
  id            bigint generated by default as identity primary key,
  nombre        text        not null,
  telefono      text        not null default '',
  email         text        not null default '',
  tipo          text        not null default 'contacto',
  -- tipo: 'valoracion' | 'contacto' | 'interes_propiedad' | 'visita'
  mensaje       text        null,
  propiedad_ref text        null,   -- ref de la propiedad si aplica
  estado        text        not null default 'nuevo',
  -- estado: 'nuevo' | 'contactado' | 'en_proceso' | 'cerrado' | 'descartado'
  notas         text        null,
  created_at    timestamptz not null default now()
);

alter table public.leads enable row level security;

create policy "Admin puede todo en leads"
  on public.leads for all
  using (true)
  with check (true);

-- Inserción pública (desde formularios web — solo insert, no select/update/delete)
create policy "Web puede insertar leads"
  on public.leads for insert
  with check (true);

-- ── Tabla visitas ────────────────────────────────────────────────────────────
create table if not exists public.visitas (
  id            bigint generated by default as identity primary key,
  propiedad_ref text        not null,
  propiedad_titulo text     not null default '',
  nombre        text        not null,
  telefono      text        not null default '',
  email         text        not null default '',
  fecha         date        not null,
  hora          time        not null,
  estado        text        not null default 'pendiente',
  -- estado: 'pendiente' | 'confirmada' | 'realizada' | 'cancelada'
  notas         text        null,
  created_at    timestamptz not null default now()
);

alter table public.visitas enable row level security;

create policy "Admin puede todo en visitas"
  on public.visitas for all
  using (true)
  with check (true);

create policy "Web puede insertar visitas"
  on public.visitas for insert
  with check (true);
